### ISSUE TITLE
Support adding users to Linux groups

### ISSUE THREAD

**Issue by p5** [ublue-os/yafti#117]
Some services (LXC and Docker) work best when the user is added to the respective groups.  Otherwise you must run with `sudo` for each command.  We can add groups in the Containerfile, but since the user does not exist, there's currently no easy way to script automatically adding the users to these groups.  

It would be great if there was a configuration screen where you can assign your user to these groups - assuming the user has sudo permissions.  

Otherwise this would need to be added to the pre/post install steps, and it would be less configurable.

**Comment by orowith2os** [comment]
As I understand it, this isn't really possible without a password prompt. I'm not sure if that UX is what's best, definitely would be annoying. If you've got any ideas, though, do speak em.

**Comment by EinoHR** [comment]
Well, a policykit daemon should be included in all DEs so a password prompt shouldn't be an issue. It might "hurt the UX" but it's necessary, and way better UX than making some user add themselves to the group manually.

**Comment by qoijjj** [comment]
Having polkit integration would be incredibly valuable for a number of use cases and especially for nvidia images, it would make the installation process even easier for new users.

Instead of running kargs and mokutil commands themselves, if yafti had polkit integration it could detect if nvidia is installed, prompt to rebase to an nvidia image, then after rebase and reboot prompt to set kargs for nvidia etc.
